import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <head />
        <body>
        <Header />
        <div>
            <main>
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
